server:
  port: 8762
eureka:
  instance:
    hostname: server2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalut-zone: http://admin:123456@server1:8761/eureka/